DROP TABLE IF EXISTS RentBook;
DROP TABLE IF EXISTS ServiceBook;
DROP TABLE IF EXISTS DetailForBicycle;
DROP TABLE IF EXISTS Detail;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Bicycle;
